### PR TITLE
Add FlushAll Api

### PR DESCRIPTION
**Pull request by bigsheeper**
issue: https://github.com/milvus-io/milvus/issues/22921

### CODE REVIEW

**Comment by bigsheeper** [comment]
issue: https://github.com/milvus-io/milvus/issues/22921

**Comment by bigsheeper** [comment]
issue: https://github.com/milvus-io/milvus-proto/issues/123

**Comment by bigsheeper** [comment]
issue: #122

**Comment by Bennu-Li** [comment]
[22921](https://github.com/milvus-io/milvus/issues/22921)

**Comment by Bennu-Li** [comment]
[#22921](https://github.com/milvus-io/milvus/issues/22921)

**Comment by bigsheeper** [comment]
#123

**Pull request merged**
