### PR TITLE
Update proto files

### PR DESCRIPTION
**Pull request by czs007**
fix: #16 #17 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
@czs007 Is `nq` a must parameter for each request?

**Comment by czs007** [comment]
> 

optional.

**Comment by czs007** [comment]
> @czs007 Is `nq` a must parameter for each request?

It's optional for old sdk, but a must for new sdk.

**Comment by jennyli-z** [comment]
fix #17

**Pull request merged**
